permalink: /:year:month:day/:title
url: https://amshq.amsl.ir
baseurl: 

# variables
name: AMSHQ
description: Wrecked AMS Head Quarter
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true